name: 'Build Chocofi Bry'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      custom_config: '["#define MIRYOKU_LAYOUTMAPPING_MINIDOX"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
