name: 'Build Chocofi Bry'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      custom_config: '["#define MIRYOKU_LAYOUTMAPPING_MINIDOX"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'
      alphas: '["qwerty"]'
